wandb_version: 1

epochs:
  desc: null
  value: 30
batch_size:
  desc: null
  value: 25
learning_rate:
  desc: null
  value: 0.0001
dataset:
  desc: null
  value: Dichtflächen
data_dir:
  desc: null
  value: data/data_modified/Dichtflächen_Cropped/processed_NIO
model_name:
  desc: null
  value: UNetBatchNorm
num_classes:
  desc: null
  value: 1
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1724864486
    t:
      1:
      - 1
      - 41
      - 55
      - 105
      2:
      - 1
      - 41
      - 55
      - 105
      3:
      - 16
      - 23
      4: 3.10.14
      5: 0.17.7
      8:
      - 3
      - 5
      13: windows-amd64
